import * as fs from "node:fs/promises";
import * as path from "node:path";
import { GtdStatus } from "../gtd/types";
import { upsertSessionTodolistNoteIndex } from "./indexStore";
import {
  sessionNoteRelDir,
  sessionTodolistAbsPath,
  sessionTodolistRelMdPath
} from "./paths";

export interface TodolistRenderInput {
  provider: string;
  sessionId: string;
  title: string;
  projectPath: string;
  gtd: GtdStatus;
  reason: string;
  tasks: string[];
  sourceMemoryIds: string[];
  previousStatus: GtdStatus | null;
  /** Override applied-at timestamp (ISO). Default now. */
  appliedAtIso?: string;
}

export interface WriteTodolistInput extends TodolistRenderInput {
  panelHome: string;
  dbPath: string;
}

/** Pure markdown renderer (no disk I/O) for preview. */
export function renderSessionTodolistMarkdown(input: TodolistRenderInput): string {
  const iso = input.appliedAtIso || new Date().toISOString();
  const tasks =
    input.tasks.length > 0
      ? input.tasks.map((t) => `- [ ] ${t}`).join("\n")
      : "- [ ] (no explicit tasks extracted — review session / digests)";

  const sources =
    input.sourceMemoryIds.length > 0
      ? input.sourceMemoryIds.map((id) => `- \`${id}\``).join("\n")
      : "- (none listed)";

  const prev = input.previousStatus == null ? "(none)" : `@${input.previousStatus}`;

  return [
    `# Todo · ${input.title}`,
    "",
    `> **Generated by AI** (Agent Resume Desktop · Memory→GTD pipeline)`,
    `> Applied at: ${iso}`,
    `> GTD status set by AI: **@${input.gtd}** (previous: ${prev})`,
    `> Do not assume human triage unless reviewed.`,
    "",
    `Session: \`${input.provider}\` \`${input.sessionId}\``,
    `Project: \`${input.projectPath || "?"}\``,
    "",
    "## Tasks",
    tasks,
    "",
    "## Why (from memory)",
    input.reason?.trim() || "(no reason)",
    "",
    "## Sources",
    sources,
    "",
    "---",
    "This file and GTD status were written automatically by AI. You may edit GTD in the VS Code extension; re-running sync may overwrite this file and GTD again.",
    ""
  ].join("\n");
}

export async function writeSessionTodolistMd(input: WriteTodolistInput): Promise<string> {
  const absPath = sessionTodolistAbsPath(input.panelHome, input.provider, input.sessionId);
  const relMdPath = sessionTodolistRelMdPath(input.provider, input.sessionId).replace(/\\/g, "/");
  const relDir = sessionNoteRelDir(input.provider, input.sessionId).replace(/\\/g, "/");
  const body = renderSessionTodolistMarkdown(input);

  await fs.mkdir(path.dirname(absPath), { recursive: true });
  await fs.writeFile(absPath, body, "utf8");
  const stat = await fs.stat(absPath);

  try {
    await upsertSessionTodolistNoteIndex(input.dbPath, {
      provider: input.provider,
      sessionId: input.sessionId,
      projectPath: input.projectPath || "",
      relDir,
      relMdPath,
      title: `Todo list (AI) · ${input.title}`,
      contentPreview: body,
      mtimeMs: stat.mtimeMs
    });
  } catch {
    // Index best-effort
  }

  return absPath;
}
