packages:
  - apps/*
  - packages/*

nodeLinker: isolated
registry: https://registry.npmjs.org/

allowBuilds:
  "@vscode/vsce-sign": true
  electron: true
  esbuild: true
  inotify: set this to true or false
  keytar: true
  node-pty: true
