#!/usr/bin/env node

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const extensionRoot = path.join(scriptDir, "..");
const repoRoot = path.join(extensionRoot, "..", "..");
export const stagingRoot = path.join(extensionRoot, ".pack-staging");

const COPY_DIRS = ["out", "locales", "media", "resources"];
/** VS Code extension details tabs read these from the VSIX root. */
const COPY_FILES = ["README.md", "CHANGELOG.md"];

function copyDir(src, dest) {
  fs.cpSync(src, dest, { recursive: true });
}

function copyExtensionFiles(targetRoot) {
  for (const file of COPY_FILES) {
    const src = path.join(extensionRoot, file);
    if (!fs.existsSync(src)) {
      throw new Error(`Missing apps/extension/${file} — required for VSIX README/Changelog tabs.`);
    }
    fs.copyFileSync(src, path.join(targetRoot, file));
  }
}

function writeStagingPackagingFiles(targetRoot) {
  const vscodeignore = `# Generated by stage-vsix.mjs — vsce ignores node_modules by default
node_modules/**
!node_modules/**
pnpm-lock.yaml
pnpm-workspace.yaml
.pnpm/**
.pnpm-workspace-state-v1.json
`;
  fs.writeFileSync(path.join(targetRoot, ".vscodeignore"), vscodeignore);
  fs.writeFileSync(
    path.join(targetRoot, "pnpm-workspace.yaml"),
    "packages:\n  - .\n\nnodeLinker: hoisted\n\nallowBuilds: {}\n"
  );
}

function buildStagingPackageJson(extensionPkg) {
  const deps = { ...extensionPkg.dependencies };
  delete deps["@agent-resume/core"];

  const corePkg = JSON.parse(fs.readFileSync(path.join(repoRoot, "packages", "core", "package.json"), "utf8"));
  for (const [name, version] of Object.entries(corePkg.dependencies ?? {})) {
    deps[name] ??= version;
  }

  return {
    name: extensionPkg.name,
    version: extensionPkg.version,
    publisher: extensionPkg.publisher,
    displayName: extensionPkg.displayName,
    description: extensionPkg.description,
    engines: extensionPkg.engines,
    categories: extensionPkg.categories,
    keywords: extensionPkg.keywords,
    icon: extensionPkg.icon,
    activationEvents: extensionPkg.activationEvents,
    main: extensionPkg.main,
    contributes: extensionPkg.contributes,
    repository: extensionPkg.repository,
    homepage: extensionPkg.homepage,
    bugs: extensionPkg.bugs,
    author: extensionPkg.author,
    license: extensionPkg.license,
    packageManager: "pnpm@11.13.1",
    dependencies: deps
  };
}

function vendorCore(targetRoot) {
  const coreDist = path.join(repoRoot, "packages", "core", "dist");
  const target = path.join(targetRoot, "node_modules", "@agent-resume", "core");
  fs.mkdirSync(target, { recursive: true });

  const corePkg = JSON.parse(fs.readFileSync(path.join(repoRoot, "packages", "core", "package.json"), "utf8"));
  const vendoredCorePkg = {
    name: corePkg.name,
    version: corePkg.version,
    main: corePkg.main,
    types: corePkg.types,
    exports: corePkg.exports,
    dependencies: corePkg.dependencies
  };
  fs.writeFileSync(path.join(target, "package.json"), `${JSON.stringify(vendoredCorePkg, null, 2)}\n`);
  copyDir(coreDist, path.join(target, "dist"));
}

export function stageVsix({ clean = true } = {}) {
  const coreDist = path.join(repoRoot, "packages", "core", "dist");
  if (!fs.existsSync(coreDist)) {
    throw new Error(`Missing core build output: ${coreDist}. Run pnpm run build:core first.`);
  }

  if (clean && fs.existsSync(stagingRoot)) {
    fs.rmSync(stagingRoot, { recursive: true, force: true });
  }
  fs.mkdirSync(stagingRoot, { recursive: true });

  for (const dir of COPY_DIRS) {
    const src = path.join(extensionRoot, dir);
    if (!fs.existsSync(src)) {
      throw new Error(`Missing ${dir}/ — run pnpm run compile first.`);
    }
    copyDir(src, path.join(stagingRoot, dir));
  }

  copyExtensionFiles(stagingRoot);

  const extensionPkg = JSON.parse(fs.readFileSync(path.join(extensionRoot, "package.json"), "utf8"));
  const stagingPkg = buildStagingPackageJson(extensionPkg);
  fs.writeFileSync(path.join(stagingRoot, "package.json"), `${JSON.stringify(stagingPkg, null, 2)}\n`);

  writeStagingPackagingFiles(stagingRoot);

  execFileSync("corepack", ["pnpm@11.13.1", "install", "--prod", "--lockfile-only"], {
    cwd: stagingRoot,
    stdio: "inherit"
  });
  execFileSync("corepack", ["pnpm@11.13.1", "install", "--prod", "--frozen-lockfile"], {
    cwd: stagingRoot,
    stdio: "inherit"
  });

  vendorCore(stagingRoot);

  return stagingRoot;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  stageVsix();
  console.log(`Staged VSIX payload at ${stagingRoot}`);
}
