import { useCallback, useEffect, useState, type ReactNode } from "react";
import { ExternalLink, FileText, MessageSquareWarning, ShieldCheck } from "lucide-react";
import type { PanelSettings } from "@agent-resume/core";
import { desktopApi } from "../../bridge";
import { Status, type StatusKind } from "../../components/Status";
import type { ReportDraft, StorageDraft, WorkbenchDraft } from "./model";

type Translate = (key: string, ...args: Array<string | number>) => string;

function ToggleRow({ title, description, checked, onChange }: { title: string; description?: string; checked: boolean; onChange: (checked: boolean) => void }) {
  return <label className="settings-row"><span className="settings-row-label"><span className="settings-row-title">{title}</span>{description ? <span className="settings-row-desc">{description}</span> : null}</span><span className="settings-toggle"><input type="checkbox" role="switch" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span className="settings-toggle-track" aria-hidden="true" /></span></label>;
}

function SelectRow({ title, description, value, onChange, children }: { title: string; description?: string; value: string | number; onChange: (value: string) => void; children: ReactNode }) {
  return <label className="settings-row"><span className="settings-row-label"><span className="settings-row-title">{title}</span>{description ? <span className="settings-row-desc">{description}</span> : null}</span><select className="settings-row-control" value={value} onChange={(event) => onChange(event.target.value)}>{children}</select></label>;
}

export function WorkbenchPane({ draft, setDraft, scheduleSave, t }: { draft: WorkbenchDraft; setDraft: (value: WorkbenchDraft) => void; scheduleSave: (value: WorkbenchDraft) => void; t: Translate }) {
  const update = <K extends keyof WorkbenchDraft>(key: K, value: WorkbenchDraft[K]) => {
    const next = { ...draft, [key]: value };
    setDraft(next);
    scheduleSave(next);
  };
  return <>
    <section className="settings-group"><h3 className="settings-group-title">{t("desktop.settings.newSessionGroup")}</h3><div className="settings-group-body">
      <SelectRow title={t("desktop.settings.defaultAgent")} description={t("desktop.settings.defaultAgentDesc")} value={draft.defaultProvider} onChange={(value) => update("defaultProvider", value as WorkbenchDraft["defaultProvider"])}><option value="codex">Codex</option><option value="claude">Claude</option><option value="grok">Grok</option><option value="agy">Antigravity</option><option value="opencode">OpenCode</option><option value="pi">Pi</option></SelectRow>
      <label className="settings-field"><span className="settings-field-label">{t("desktop.settings.scratchDir")}</span><input value={draft.scratchDir} placeholder="~/.agent-resume-panel/.desktop/scratch" onChange={(event) => update("scratchDir", event.target.value)} /></label>
    </div></section>
    <section className="settings-group"><h3 className="settings-group-title">{t("desktop.settings.embeddedEditorGroup")}</h3><div className="settings-group-body">
      <ToggleRow title={t("desktop.settings.editorEditable")} description={t("desktop.settings.editorEditableDesc")} checked={draft.editorEditable} onChange={(value) => update("editorEditable", value)} />
      <label className="settings-row"><span className="settings-row-label"><span className="settings-row-title">{t("desktop.settings.editorFontSize")}</span><span className="settings-row-desc">{t("desktop.settings.editorFontSizeDesc")}</span></span><label className="settings-number-control"><input className="settings-number-input" type="number" min="11" max="24" value={draft.editorFontSize} onChange={(event) => update("editorFontSize", Number(event.target.value))} /><span aria-hidden="true">px</span></label></label>
      <ToggleRow title={t("desktop.settings.editorWordWrap")} description={t("desktop.settings.editorWordWrapDesc")} checked={draft.editorWordWrap} onChange={(value) => update("editorWordWrap", value)} />
      <SelectRow title={t("desktop.settings.editorTabSize")} description={t("desktop.settings.editorTabSizeDesc")} value={draft.editorTabSize} onChange={(value) => update("editorTabSize", Number(value) as WorkbenchDraft["editorTabSize"])}><option value="2">{t("desktop.settings.editorTabSize2")}</option><option value="4">{t("desktop.settings.editorTabSize4")}</option><option value="8">{t("desktop.settings.editorTabSize8")}</option></SelectRow>
      <SelectRow title={t("desktop.settings.editorAutoSaveDelay")} description={t("desktop.settings.editorAutoSaveDelayDesc")} value={draft.editorAutoSaveDelayMs} onChange={(value) => update("editorAutoSaveDelayMs", Number(value) as WorkbenchDraft["editorAutoSaveDelayMs"])}><option value="300">{t("desktop.settings.editorAutoSaveDelay300")}</option><option value="600">{t("desktop.settings.editorAutoSaveDelay600")}</option><option value="1000">{t("desktop.settings.editorAutoSaveDelay1000")}</option><option value="2000">{t("desktop.settings.editorAutoSaveDelay2000")}</option></SelectRow>
    </div></section>
    <section className="settings-group"><h3 className="settings-group-title">{t("desktop.settings.editorTerminal")}</h3><div className="settings-group-body">
      <SelectRow title={t("desktop.settings.projectEditor")} description={t("desktop.settings.projectEditorDesc")} value={draft.projectEditor} onChange={(value) => update("projectEditor", value as WorkbenchDraft["projectEditor"])}><option value="auto">{t("desktop.settings.editorAuto")}</option><option value="vscode">VS Code</option><option value="vscodium">VSCodium</option><option value="cursor">Cursor</option><option value="windsurf">Windsurf</option></SelectRow>
      <SelectRow title={t("desktop.settings.terminalMode")} description={t("desktop.settings.terminalModeDesc")} value={draft.terminalMode} onChange={(value) => update("terminalMode", value as WorkbenchDraft["terminalMode"])}><option value="xterm">{t("desktop.settings.terminalXterm")}</option><option value="external-system">{t("desktop.settings.terminalExternal")}</option></SelectRow>
      {draft.terminalMode === "external-system" ? <SelectRow title={t("desktop.settings.externalLaunch")} description={t("desktop.settings.externalLaunchDesc")} value={draft.externalLaunchMode} onChange={(value) => update("externalLaunchMode", value as WorkbenchDraft["externalLaunchMode"])}><option value="executeCommand">{t("desktop.settings.launchExecute")}</option><option value="pasteCommand">{t("desktop.settings.launchPaste")}</option><option value="copyCommand">{t("desktop.settings.launchCopy")}</option></SelectRow> : null}
      <SelectRow title={t("desktop.settings.cmdT")} description={t("desktop.settings.cmdTDesc")} value={draft.cmdTAction} onChange={(value) => update("cmdTAction", value as WorkbenchDraft["cmdTAction"])}><option value="newTerminal">{t("desktop.settings.cmdTNewTerminal")}</option><option value="newSession">{t("desktop.settings.cmdTNewSession")}</option></SelectRow>
    </div></section>
    <section className="settings-group"><h3 className="settings-group-title">{t("desktop.settings.gitCommitMessageGroup")}</h3><div className="settings-group-body">
      <SelectRow title={t("desktop.settings.gitCommitMessageStyle")} description={t("desktop.settings.gitCommitMessageStyleDesc")} value={draft.gitCommitMessageStyle} onChange={(value) => update("gitCommitMessageStyle", value as WorkbenchDraft["gitCommitMessageStyle"])}><option value="conventional">{t("desktop.settings.gitCommitMessageStyleConventional")}</option><option value="gitmoji">{t("desktop.settings.gitCommitMessageStyleGitmoji")}</option><option value="custom">{t("desktop.settings.gitCommitMessageStyleCustom")}</option></SelectRow>
      {draft.gitCommitMessageStyle === "custom" ? <label className="settings-field"><span className="settings-field-label">{t("desktop.settings.gitCommitCustomInstructions")}</span><span className="settings-field-desc muted">{t("desktop.settings.gitCommitCustomInstructionsDesc")}</span><textarea rows={6} maxLength={4000} spellCheck={false} value={draft.gitCommitCustomInstructions} onChange={(event) => update("gitCommitCustomInstructions", event.target.value)} /></label> : null}
    </div></section>
    <section className="settings-group"><h3 className="settings-group-title">{t("desktop.settings.gitNestedScanGroup")}</h3><div className="settings-group-body">
      <SelectRow title={t("desktop.settings.gitNestedScanMaxDepth")} description={t("desktop.settings.gitNestedScanMaxDepthDesc")} value={draft.gitNestedScanMaxDepth} onChange={(value) => update("gitNestedScanMaxDepth", Number(value))}>{Array.from({ length: 10 }, (_, index) => <option key={index + 1} value={index + 1}>{index + 1}</option>)}</SelectRow>
      <label className="settings-field"><span className="settings-field-label">{t("desktop.settings.gitNestedScanIgnoreDirs")}</span><span className="settings-field-desc muted">{t("desktop.settings.gitNestedScanIgnoreDirsDesc")}</span><textarea rows={5} spellCheck={false} placeholder={"node_modules\ndist"} value={draft.gitNestedScanIgnoreDirs} onChange={(event) => update("gitNestedScanIgnoreDirs", event.target.value)} /></label>
    </div></section>
  </>;
}

export function ReportPane({ draft, setDraft, scheduleSave, t }: { draft: ReportDraft; setDraft: (value: ReportDraft) => void; scheduleSave: (value: ReportDraft) => void; t: Translate }) {
  const [maxDays, setMaxDays] = useState(400);
  const [skipExisting, setSkipExisting] = useState(true);
  const [skipEmbedding, setSkipEmbedding] = useState(true);
  const [status, setStatus] = useState<{ text: string; kind?: StatusKind }>({ text: "" });
  const update = <K extends keyof ReportDraft>(key: K, value: ReportDraft[K]) => {
    if (key === "enabled" && value && !draft.enabled && !window.confirm(t("desktop.settings.memoryEnableConfirm"))) return;
    const next = { ...draft, [key]: value };
    setDraft(next);
    scheduleSave(next);
  };
  const preview = async () => {
    setStatus({ text: t("desktop.backfill.scanning") });
    try {
      const value = await desktopApi().previewBackfillDigests({ maxDays, skipExisting });
      setStatus({ text: t("desktop.backfill.preview", value.sessionRowsScanned, value.days.length, value.weeks.length, value.months.length, value.estimatedLlmCalls, value.days.length ? t("desktop.backfill.previewRange", value.days[0], value.days[value.days.length - 1]) : t("desktop.backfill.noActivity")), kind: value.days.length ? "ok" : "error" });
    } catch (error) { setStatus({ text: error instanceof Error ? error.message : String(error), kind: "error" }); }
  };
  const run = async () => {
    setStatus({ text: t("desktop.backfill.scanningShort") });
    try {
      const value = await desktopApi().previewBackfillDigests({ maxDays, skipExisting });
      const detail = value.days.length ? t("desktop.backfill.dateRange", value.days[0], value.days[value.days.length - 1]) : "";
      if (!window.confirm(t("desktop.backfill.confirm", value.sessionRowsScanned, value.days.length, value.weeks.length, value.months.length, value.estimatedLlmCalls, detail))) { setStatus({ text: t("desktop.backfill.cancelled") }); return; }
      setStatus({ text: t("desktop.backfill.running") });
      const result = await desktopApi().backfillDigests({ maxDays, skipExisting, skipEmbedding });
      const failures = result.daily.failed.length + result.weekly.failed.length + result.monthly.failed.length;
      setStatus({ text: `${t("desktop.backfill.stats", "daily", result.daily.ok.length, result.daily.skipped.length, failures ? `/fail ${failures}` : "", result.daily.planned.length)} · ${t("desktop.backfill.stats", "weekly", result.weekly.ok.length, result.weekly.skipped.length, "", result.weekly.planned.length)}`, kind: failures ? "error" : "ok" });
    } catch (error) { setStatus({ text: error instanceof Error ? error.message : String(error), kind: "error" }); }
  };
  return <>
    <section className="settings-group"><h3 className="settings-group-title">{t("desktop.settings.scheduledDigests")}</h3><div className="settings-group-body"><ToggleRow title={t("desktop.settings.enableSchedule")} description={t("desktop.settings.enableScheduleDesc")} checked={draft.enabled} onChange={(value) => update("enabled", value)} />{draft.enabled ? <div className="settings-schedule-fields"><label className="settings-field"><span className="settings-field-label">{t("desktop.settings.dailyHour")}</span><input type="number" min="0" max="23" value={draft.dailyHour} onChange={(event) => update("dailyHour", Number(event.target.value))} /></label><label className="settings-field"><span className="settings-field-label">{t("desktop.settings.weeklyHour")}</span><input type="number" min="0" max="23" value={draft.weeklyHour} onChange={(event) => update("weeklyHour", Number(event.target.value))} /></label><label className="settings-field"><span className="settings-field-label">{t("desktop.settings.monthlyHour")}</span><input type="number" min="0" max="23" value={draft.monthlyHour} onChange={(event) => update("monthlyHour", Number(event.target.value))} /></label></div> : null}</div></section>
    <section className="settings-group settings-group-action"><h3 className="settings-group-title">{t("desktop.settings.backfillTitle")}</h3><div className="settings-group-body"><p className="settings-callout">{t("desktop.settings.backfillCallout")}</p><label className="settings-field"><span className="settings-field-label">{t("desktop.settings.backfillMaxDays")}</span><input type="number" min="1" max="2000" value={maxDays} onChange={(event) => setMaxDays(Math.max(1, Math.min(2000, Number(event.target.value) || 400)))} /></label><ToggleRow title={t("desktop.settings.backfillSkipExisting")} checked={skipExisting} onChange={setSkipExisting} /><ToggleRow title={t("desktop.settings.backfillSkipEmbedding")} checked={skipEmbedding} onChange={setSkipEmbedding} /><div className="settings-action-row"><button type="button" className="tool-btn" onClick={() => void preview()}>{t("desktop.settings.backfillPreview")}</button><button type="button" className="tool-btn" onClick={() => void run()}>{t("desktop.settings.backfillRun")}</button></div><Status kind={status.kind}>{status.text}</Status></div></section>
  </>;
}

export function StoragePane({ draft, setDraft, scheduleSave, t }: { draft: StorageDraft; setDraft: (value: StorageDraft) => void; scheduleSave: (value: StorageDraft) => void; t: Translate }) {
  const [advanced, setAdvanced] = useState(false);
  const update = <K extends keyof StorageDraft>(key: K, value: StorageDraft[K]) => { const next = { ...draft, [key]: value }; setDraft(next); scheduleSave(next); };
  const home = draft.panelHome.trim() || "~/.agent-resume-panel";
  const paths: Array<[keyof StorageDraft, string, string]> = [["codexHome", "desktop.settings.codexHome", "~/.codex"], ["claudeHome", "desktop.settings.claudeHome", "~/.claude"], ["antigravityHome", "desktop.settings.antigravityHome", "~/.gemini"], ["grokHome", "desktop.settings.grokHome", "~/.grok"], ["almaDataDir", "desktop.settings.almaDataDir", "~/Library/Application Support/alma"], ["opencodeHome", "desktop.settings.opencodeHome", "~/.local/share/opencode"], ["piHome", "desktop.settings.piHome", "~/.pi/agent"]];
  return <>
    <section className="settings-group"><h3 className="settings-group-title">{t("desktop.settings.appData")}</h3><div className="settings-group-body"><p className="settings-footnote">{t("desktop.settings.appDataFootnote")}</p><label className="settings-field"><span className="settings-field-label">{t("desktop.settings.panelHome")}</span><input placeholder="~/.agent-resume-panel" value={draft.panelHome} onChange={(event) => update("panelHome", event.target.value)} /></label><p className="settings-footnote">{t("desktop.settings.panelHomeFootnote")}</p><div className="settings-path-row"><button type="button" className="tool-btn" onClick={() => void desktopApi().settingsOpenPanelHome()}>{t("desktop.common.revealInFinder")}</button></div></div></section>
    <section className="settings-group"><h3 className="settings-group-title">{t("desktop.settings.notesGroup")}</h3><div className="settings-group-body"><p className="settings-footnote">{t("desktop.settings.notesFootnote")}</p><div className="settings-path-row"><code className="settings-path-display">{home}/notes</code><button type="button" className="tool-btn" onClick={() => void desktopApi().notesOpenFolder()}>{t("desktop.common.revealInFinder")}</button></div></div></section>
    <section className={`settings-group settings-disclosure${advanced ? "" : " collapsed"}`}><button type="button" className="settings-disclosure-head" aria-expanded={advanced} onClick={() => setAdvanced((value) => !value)}><span className="settings-disclosure-chevron" aria-hidden="true" /><span className="settings-disclosure-title">{t("desktop.settings.agentHomesAdvanced")}</span></button>{advanced ? <div className="settings-disclosure-body">{paths.map(([key, label, placeholder]) => <label className="settings-field" key={key}><span className="settings-field-label">{t(label)}</span><input placeholder={placeholder} value={draft[key]} onChange={(event) => update(key, event.target.value)} /></label>)}</div> : null}</section>
  </>;
}

function formatNumber(value: number | null | undefined): string { return value == null || !Number.isFinite(value) ? "-" : value.toLocaleString(); }
function formatTime(value: number): string { return new Date(value).toLocaleString(); }

export function UsagePane({ t }: { t: Translate }) {
  const [days, setDays] = useState(30);
  const [data, setData] = useState<{ summary: Awaited<ReturnType<ReturnType<typeof desktopApi>["usageSummary"]>>; events: Awaited<ReturnType<ReturnType<typeof desktopApi>["usageListEvents"]>>; runs: Awaited<ReturnType<ReturnType<typeof desktopApi>["usageListScheduleRuns"]>> } | null>(null);
  const [status, setStatus] = useState<{ text: string; kind?: StatusKind }>({ text: "" });
  const load = useCallback(async () => { setStatus({ text: t("desktop.usage.loading") }); try { const [summary, events, runs] = await Promise.all([desktopApi().usageSummary({ days }), desktopApi().usageListEvents({ days, limit: 80 }), desktopApi().usageListScheduleRuns({ days, limit: 80 })]); setData({ summary, events, runs }); setStatus({ text: t("desktop.usage.summaryStatus", days, summary.eventCount), kind: "ok" }); } catch (error) { setStatus({ text: error instanceof Error ? error.message : String(error), kind: "error" }); } }, [days, t]);
  useEffect(() => { void load(); }, [load]);
  const summary = data?.summary;
  return <div className="settings-pane-body"><div className="settings-usage-toolbar"><label className="settings-inline-label"><span>{t("desktop.usage.scope")}</span><select value={days} onChange={(event) => setDays(Number(event.target.value))}><option value="7">{t("desktop.usage.last7")}</option><option value="30">{t("desktop.usage.last30")}</option><option value="90">{t("desktop.usage.last90")}</option></select></label><button type="button" className="ghost-btn" onClick={() => void load()}>{t("desktop.common.refresh")}</button></div><div className="usage-cards"><div className="usage-card"><div className="label">{t("desktop.usage.totalTokens")}</div><div className="value">{formatNumber(summary?.totalTokens)}</div></div><div className="usage-card"><div className="label">{t("desktop.usage.promptCompletion")}</div><div className="value usage-value-small">{formatNumber(summary?.promptTokens)} / {formatNumber(summary?.completionTokens)}</div></div><div className="usage-card"><div className="label">{t("desktop.usage.chatEmbed")}</div><div className="value usage-value-small">{formatNumber(summary?.chatTokens)} / {formatNumber(summary?.embeddingTokens)}</div></div><div className="usage-card"><div className="label">{t("desktop.usage.events")}</div><div className="value">{formatNumber(summary?.eventCount)}</div></div><div className="usage-card usage-card-wide"><div className="label">{t("desktop.usage.bySource")}</div><div className="value usage-value-small">{summary?.bySource.slice(0, 4).map((item) => `${item.source}:${item.totalTokens}`).join(" · ") || "-"}</div></div></div><UsageTable title={t("desktop.usage.byDay")} headings={[t("desktop.usage.colDate"), t("desktop.usage.colTokens"), t("desktop.usage.colCalls"), t("desktop.usage.colScheduleRuns")]} rows={summary?.byDay.map((item) => [item.day, formatNumber(item.totalTokens), formatNumber(item.events), formatNumber(item.scheduleRuns)]) || []} empty={t("desktop.usage.noData")} /><UsageTable title={t("desktop.usage.scheduleLog")} headings={[t("desktop.usage.colTime"), t("desktop.usage.colLevel"), t("desktop.usage.colPeriod"), t("desktop.usage.colStatus"), t("desktop.usage.colTokens"), t("desktop.usage.colError")]} rows={data?.runs.map((item) => [formatTime(item.startedAtMs), item.level, item.periodKey, item.status, formatNumber(item.totalTokens), item.error || ""]) || []} empty={t("desktop.usage.noScheduleRuns")} /><UsageTable title={t("desktop.usage.llmDetails")} headings={[t("desktop.usage.colTime"), t("desktop.usage.colKind"), t("desktop.usage.colSource"), t("desktop.usage.colModel"), t("desktop.usage.colTokens"), t("desktop.usage.colMs")]} rows={data?.events.map((item) => [formatTime(item.createdAtMs), item.kind, `${item.source}${item.jobKey ? ` · ${item.jobKey}` : ""}`, item.model || "", formatNumber(item.totalTokens), formatNumber(item.durationMs)]) || []} empty={t("desktop.usage.noLlmEvents")} /><Status kind={status.kind}>{status.text}</Status></div>;
}

function UsageTable({ title, headings, rows, empty }: { title: string; headings: string[]; rows: string[][]; empty: string }) { return <><h3 className="section-h">{title}</h3><div className="table-wrap compact"><table><thead><tr>{headings.map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={index}>{row.map((value, cell) => <td key={cell}>{value}</td>)}</tr>) : <tr><td colSpan={headings.length} className="muted">{empty}</td></tr>}</tbody></table></div></>; }

export function AboutPane({ t }: { t: Translate }) {
  const [version, setVersion] = useState("");
  const [update, setUpdate] = useState<Awaited<ReturnType<ReturnType<typeof desktopApi>["checkForUpdate"]>> | null>(null);
  const [checking, setChecking] = useState(false);
  const check = useCallback(async (force = false) => { setChecking(true); try { setUpdate(await desktopApi().checkForUpdate({ force })); } finally { setChecking(false); } }, []);
  useEffect(() => { void desktopApi().getAppVersion().then(setVersion); void check(); }, [check]);
  const available = Boolean(update?.ok && update.updateAvailable && update.latestVersion && update.latestVersion !== update.currentVersion);
  const updateUrl = update?.ok ? update.downloadUrl || update.releaseUrl || "" : "";
  const open = (url: string) => void desktopApi().openExternalUrl(url);
  const resource = (title: string, description: string, icon: ReactNode, url: string, primary = false) => <button type="button" className={`settings-about-row${primary ? " settings-about-row-primary" : ""}`} onClick={() => open(url)}><span className="settings-about-row-icon" aria-hidden="true">{icon}</span><span className="settings-about-row-text"><span className="settings-about-row-title">{title}</span><span className="settings-about-row-desc">{description}</span></span><ExternalLink className="settings-about-row-external" size={14} aria-hidden="true" /></button>;
  return <div className="settings-pane-body settings-about-body"><header className="settings-about-hero"><div className="settings-about-app-icon" aria-hidden="true"><img className="settings-about-app-icon-img" src="../resources/icon.png" alt="" width="72" height="72" decoding="async" /></div><h3 className="settings-about-app-name">Agent Resume</h3><p className="settings-about-version">{t("desktop.settings.aboutVersionLabel")} {version || "-"}</p><p className="settings-about-tagline">{t("desktop.settings.aboutTagline")}</p></header>{checking || update ? <div className={`settings-about-update${available ? " is-available" : ""}`}><p className="settings-about-update-text">{checking ? t("desktop.settings.updateChecking") : !update?.ok ? t("desktop.settings.updateCheckFailed") : available ? t("desktop.settings.updateAvailable", update.latestVersion || "") : t("desktop.settings.updateUpToDate")}</p><div className="settings-about-update-actions">{available && updateUrl ? <button type="button" className="btn primary" onClick={() => open(updateUrl)}>{t("desktop.settings.updateDownload")}</button> : null}<button type="button" className="btn ghost" onClick={() => void check(true)}>{t("desktop.settings.updateRecheck")}</button></div></div> : null}<section className="settings-group"><h3 className="settings-group-title">{t("desktop.settings.aboutResources")}</h3><div className="settings-group-body settings-group-body-rows settings-about-rows">{resource(t("desktop.settings.linkDocumentation"), t("desktop.settings.linkDocumentationDesc"), <FileText size={18} />, "https://github.com/thunder-luc/agent-resume-desktop-doc#readme")}{resource(t("desktop.settings.linkExtensionDoc"), t("desktop.settings.linkExtensionDocDesc"), <ExternalLink size={18} />, "https://github.com/thunder-luc/agent-resume-panel-doc#readme")}</div></section><section className="settings-group"><h3 className="settings-group-title">{t("desktop.settings.aboutFeedback")}</h3><div className="settings-group-body settings-group-body-rows settings-about-rows">{resource(t("desktop.settings.linkReportIssue"), t("desktop.settings.linkReportIssueDesc"), <MessageSquareWarning size={18} />, "https://github.com/thunder-luc/agent-resume-desktop-doc/issues", true)}</div></section><aside className="settings-about-privacy"><ShieldCheck className="settings-about-privacy-icon" size={16} aria-hidden="true" /><p>{t("desktop.settings.footerHint")}</p></aside></div>;
}
