import { BrowserWindow } from "electron";
import { execFile } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { promisify } from "node:util";
import * as pty from "node-pty";
import { expandHome } from "@agent-resume/core";
import { safeHandle } from "./ipcUtils";

const execFileAsync = promisify(execFile);

interface PtySession {
  pty: pty.IPty;
  respawnOnExit: boolean;
  lastSpawnCwd: string;
  lastCols: number;
  lastRows: number;
  shell: string;
  startedAt: number;
}

const ptySessions = new Map<number, PtySession>();
let nextTerminalId = 0;

function ensureSpawnHelperExecutable(): void {
  if (process.platform !== "darwin" && process.platform !== "linux") return;
  try {
    const entry = require.resolve("node-pty");
    const moduleRoot = path.resolve(path.dirname(entry), "..");
    const writableRoot = moduleRoot
      .replace("app.asar", "app.asar.unpacked")
      .replace("node_modules.asar", "node_modules.asar.unpacked");
    const helpers = [
      path.join(writableRoot, "build", "Release", "spawn-helper"),
      path.join(writableRoot, "build", "Debug", "spawn-helper")
    ];
    const prebuildsRoot = path.join(writableRoot, "prebuilds");
    if (fs.existsSync(prebuildsRoot)) {
      for (const dir of fs.readdirSync(prebuildsRoot, { withFileTypes: true })) {
        if (dir.isDirectory() && dir.name.startsWith(`${process.platform}-`)) {
          helpers.push(path.join(prebuildsRoot, dir.name, "spawn-helper"));
        }
      }
    }
    for (const helperPath of helpers) {
      if (!fs.existsSync(helperPath)) continue;
      const mode = fs.statSync(helperPath).mode;
      if ((mode & 0o111) === 0) {
        fs.chmodSync(helperPath, mode | 0o755);
      }
    }
  } catch {
    // spawn will surface a descriptive error if helper is still unusable
  }
}

ensureSpawnHelperExecutable();

const FALLBACK_SHELLS = [
  "/bin/zsh",
  "/bin/bash",
  "/opt/homebrew/bin/zsh",
  "/usr/local/bin/zsh"
];

function isExecutable(filePath: string): boolean {
  try {
    fs.accessSync(filePath, fs.constants.X_OK);
    return true;
  } catch {
    return false;
  }
}

function findExecutableInPath(name: string, extraDirs: string[]): string | null {
  const dirs = new Set<string>();
  for (const dir of (process.env.PATH || "").split(path.delimiter)) {
    if (dir) dirs.add(dir);
  }
  for (const dir of extraDirs) {
    dirs.add(dir);
  }

  for (const dir of dirs) {
    const full = path.join(dir, name);
    if (isExecutable(full)) return full;
  }
  return null;
}

function resolveShell(): string {
  const candidate = process.env.SHELL?.trim() || "";
  if (candidate) {
    const expanded = expandHome(candidate);
    if (path.isAbsolute(expanded) && isExecutable(expanded)) {
      return expanded;
    }
    const fromPath = findExecutableInPath(path.basename(candidate), [
      "/opt/homebrew/bin",
      "/usr/local/bin",
      "/usr/bin",
      "/bin"
    ]);
    if (fromPath) return fromPath;
  }

  for (const shell of FALLBACK_SHELLS) {
    if (isExecutable(shell)) return shell;
  }

  return "/bin/zsh";
}

function resolveCwd(raw?: string): string {
  const cwd = expandHome(raw?.trim() || process.cwd());
  try {
    const stat = fs.statSync(cwd);
    if (!stat.isDirectory()) {
      throw new Error(`工作目录不是文件夹: ${cwd}`);
    }
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code === "ENOENT") {
      throw new Error(`工作目录不存在: ${cwd}`);
    }
    throw error;
  }
  return cwd;
}

function shellKind(shell: string): "zsh" | "bash" | "other" {
  const base = path.basename(shell).toLowerCase();
  if (base.includes("zsh")) return "zsh";
  if (base.includes("bash")) return "bash";
  return "other";
}

function ensureZdotDir(integrationScript: string): string {
  const dir = path.join(os.tmpdir(), "agent-resume-zdot");
  fs.mkdirSync(dir, { recursive: true });
  const homeZshrc = path.join(os.homedir(), ".zshrc");
  const content = [
    "# Generated by Agent Resume — embedded terminal cwd integration",
    `[ -f "${integrationScript}" ] && . "${integrationScript}"`,
    `[ -f "${homeZshrc}" ] && . "${homeZshrc}"`
  ].join("\n");
  fs.writeFileSync(path.join(dir, ".zshrc"), `${content}\n`, "utf8");
  return dir;
}

function resolveIntegrationScript(): string | null {
  if (process.platform !== "darwin" && process.platform !== "linux") return null;
  const candidates = [
    path.join(__dirname, "shellIntegration", "integration.sh"),
    path.join(__dirname, "..", "main", "shellIntegration", "integration.sh"),
    path.join(__dirname, "..", "..", "src", "main", "shellIntegration", "integration.sh")
  ];
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

function envWithPath(integrationScript: string | null, shell: string): Record<string, string> {
  const env = { ...process.env } as Record<string, string>;
  const home = os.homedir();
  const extra = [
    "/opt/homebrew/bin",
    "/usr/local/bin",
    "/usr/bin",
    "/bin",
    path.join(home, ".local/bin"),
    path.join(home, ".npm-global/bin")
  ];
  const merged = (env.PATH || "").split(path.delimiter).filter(Boolean);
  for (const dir of extra) {
    if (!merged.includes(dir) && fs.existsSync(dir)) {
      merged.push(dir);
    }
  }
  env.PATH = merged.join(path.delimiter);
  if (!env.HOME) env.HOME = home;
  if (!env.TERM) env.TERM = "xterm-256color";
  if (integrationScript) {
    env.AGENT_RESUME_SHELL_INTEGRATION = integrationScript;
    env.TERM_PROGRAM = "AgentResume";
    if (shellKind(shell) === "zsh") {
      env.ZDOTDIR = ensureZdotDir(integrationScript);
    }
  }
  return env;
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function buildShellLaunchArgs(
  shell: string,
  integrationScript: string | null,
  command?: string
): string[] {
  const quotedShell = shellQuote(shell);
  const cmd = command?.trim();
  const kind = shellKind(shell);

  if (integrationScript) {
    const quotedIntegration = shellQuote(integrationScript);
    if (cmd) {
      if (kind === "zsh") {
        // ZDOTDIR in env reloads integration after exec.
        return ["-ilc", `source ${quotedIntegration}; ${cmd}; exec ${quotedShell} -il`];
      }
      if (kind === "bash") {
        return [
          "-ic",
          `source ${quotedIntegration}; ${cmd}; exec ${quotedShell} -i --init-file ${quotedIntegration}`
        ];
      }
      return ["-ic", `source ${quotedIntegration}; ${cmd}; exec ${quotedShell} -i`];
    }

    // Interactive shells must not use -c (would exit immediately and respawn forever).
    if (kind === "bash") {
      return ["-i", "--init-file", integrationScript];
    }
    if (kind === "zsh") {
      return ["-il"];
    }
    return [];
  }

  if (cmd) {
    return ["-ic", `${cmd}; exec ${quotedShell}`];
  }
  return [];
}

function spawnPty(
  shell: string,
  cwd: string,
  cols: number,
  rows: number,
  command?: string
): pty.IPty {
  const integrationScript = resolveIntegrationScript();
  const env = envWithPath(integrationScript, shell);
  const args = buildShellLaunchArgs(shell, integrationScript, command);
  return pty.spawn(shell, args, {
    name: "xterm-256color",
    cols,
    rows,
    cwd,
    env
  });
}

function formatExecError(error: unknown): string {
  const err = error as NodeJS.ErrnoException & { stderr?: string | Buffer };
  const stderr = err.stderr ? String(err.stderr).trim() : "";
  if (stderr) return stderr;
  if (error instanceof Error && error.message) return error.message;
  return String(error);
}

function isValidGitBranchRef(branch: string): boolean {
  const trimmed = branch.trim();
  if (!trimmed || trimmed.startsWith("-")) return false;
  if (/[\0\r\n]/.test(trimmed)) return false;
  return true;
}

async function queryGitInfo(cwd: string): Promise<{ isRepo: boolean; branch: string | null }> {
  try {
    const { stdout } = await execFileAsync("git", ["-C", cwd, "rev-parse", "--is-inside-work-tree"], {
      timeout: 3000,
      maxBuffer: 4096
    });
    if (stdout.trim() !== "true") {
      return { isRepo: false, branch: null };
    }
  } catch {
    return { isRepo: false, branch: null };
  }

  try {
    const { stdout } = await execFileAsync("git", ["-C", cwd, "rev-parse", "--abbrev-ref", "HEAD"], {
      timeout: 3000,
      maxBuffer: 4096
    });
    const branch = stdout.trim() || null;
    return { isRepo: true, branch };
  } catch {
    return { isRepo: true, branch: null };
  }
}

async function listGitBranches(
  cwd: string
): Promise<{ current: string | null; branches: string[] }> {
  try {
    const { stdout } = await execFileAsync("git", ["-C", cwd, "branch", "--list"], {
      timeout: 5000,
      maxBuffer: 1024 * 1024
    });
    const branches: string[] = [];
    let current: string | null = null;
    for (const line of stdout.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      if (trimmed.startsWith("* ")) {
        current = trimmed.slice(2).trim();
        branches.push(current);
      } else {
        branches.push(trimmed);
      }
    }
    return { current, branches };
  } catch (error) {
    throw new Error(formatExecError(error));
  }
}

async function checkoutGitBranch(cwd: string, branch: string): Promise<void> {
  if (!isValidGitBranchRef(branch)) {
    throw new Error(`无效的分支名: ${branch}`);
  }
  try {
    await execFileAsync("git", ["-C", cwd, "checkout", branch.trim()], {
      timeout: 15000,
      maxBuffer: 1024 * 1024
    });
  } catch (error) {
    throw new Error(formatExecError(error));
  }
}

function attachPtyHandlers(
  ptyInstance: pty.IPty,
  id: number,
  win: BrowserWindow | null
): void {
  ptyInstance.onData((data) => {
    if (win && !win.isDestroyed()) {
      win.webContents.send("terminal:data", { id, data });
    }
  });
  ptyInstance.onExit(() => {
    const session = ptySessions.get(id);
    if (!session) return;

    const { respawnOnExit, lastSpawnCwd, lastCols, lastRows, shell, startedAt } = session;
    ptySessions.delete(id);

    const livedMs = Date.now() - startedAt;
    if (respawnOnExit && lastSpawnCwd && livedMs >= 400) {
      try {
        const newPty = spawnPty(shell, lastSpawnCwd, lastCols, lastRows);
        ptySessions.set(id, {
          pty: newPty,
          respawnOnExit: true,
          lastSpawnCwd,
          lastCols,
          lastRows,
          shell,
          startedAt: Date.now()
        });
        attachPtyHandlers(newPty, id, win);
        if (win && !win.isDestroyed()) {
          win.webContents.send("terminal:respawned", { id });
        }
        return;
      } catch (error) {
        console.warn("terminal respawn failed:", error);
      }
    } else if (respawnOnExit && livedMs < 400) {
      console.warn(`terminal ${id} exited too quickly (${livedMs}ms); skipping respawn`);
    }

    if (win && !win.isDestroyed()) {
      win.webContents.send("terminal:exit", { id });
    }
  });
}

function destroyPtyById(id: number): void {
  const session = ptySessions.get(id);
  if (!session) return;
  session.respawnOnExit = false;
  try {
    session.pty.kill();
  } catch {
    // ignore
  }
  ptySessions.delete(id);
}

export function registerPtyIpc(getWindow: () => BrowserWindow | null): void {
  safeHandle(
    "terminal:spawn",
    async (
      _event,
      args: { cwd: string; command?: string; cols?: number; rows?: number }
    ) => {
      const shell = resolveShell();
      const cols = Math.max(2, Math.floor(args.cols || 80));
      const rows = Math.max(2, Math.floor(args.rows || 24));
      const cwd = resolveCwd(args.cwd);
      const id = ++nextTerminalId;
      const win = getWindow();

      let ptyInstance: pty.IPty;
      try {
        ptyInstance = spawnPty(shell, cwd, cols, rows, args.command);
      } catch (error) {
        const detail = error instanceof Error ? error.message : String(error);
        throw new Error(`无法启动终端 (shell=${shell}, cwd=${cwd}): ${detail}`);
      }

      ptySessions.set(id, {
        pty: ptyInstance,
        respawnOnExit: true,
        lastSpawnCwd: cwd,
        lastCols: cols,
        lastRows: rows,
        shell,
        startedAt: Date.now()
      });
      attachPtyHandlers(ptyInstance, id, win);

      return { id };
    }
  );

  safeHandle("terminal:input", (_event, args: { id: number; data: string }) => {
    const session = ptySessions.get(Math.floor(args.id));
    session?.pty.write(args.data);
    return { ok: true };
  });

  safeHandle("terminal:resize", (_event, args: { id: number; cols: number; rows: number }) => {
    const id = Math.floor(args.id);
    const session = ptySessions.get(id);
    const cols = Math.max(2, Math.floor(args.cols || 80));
    const rows = Math.max(2, Math.floor(args.rows || 24));
    if (session) {
      session.lastCols = cols;
      session.lastRows = rows;
      session.pty.resize(cols, rows);
    }
    return { ok: true };
  });

  safeHandle("terminal:destroy", (_event, args: { id: number }) => {
    destroyPtyById(Math.floor(args.id));
    return { ok: true };
  });

  safeHandle("terminal:gitInfo", async (_event, args: { cwd: string }) => {
    const cwd = resolveCwd(args.cwd);
    return queryGitInfo(cwd);
  });

  safeHandle("terminal:gitBranches", async (_event, args: { cwd: string }) => {
    const cwd = resolveCwd(args.cwd);
    const info = await queryGitInfo(cwd);
    if (!info.isRepo) {
      return { current: null, branches: [] as string[] };
    }
    return listGitBranches(cwd);
  });

  safeHandle("terminal:gitCheckout", async (_event, args: { cwd: string; branch: string }) => {
    const cwd = resolveCwd(args.cwd);
    const info = await queryGitInfo(cwd);
    if (!info.isRepo) {
      throw new Error("当前目录不是 Git 仓库");
    }
    await checkoutGitBranch(cwd, args.branch);
    const refreshed = await queryGitInfo(cwd);
    return { branch: refreshed.branch };
  });
}

export function destroyPtyOnQuit(): void {
  for (const id of [...ptySessions.keys()]) {
    destroyPtyById(id);
  }
}