import { BuildHandoffBriefOptions } from "./types";
import { buildResumeCommandFromRef } from "./resumeCommand";

/**
 * Template handoff brief from Meta-Agent answer + memory citations (no extra LLM call).
 */
export function buildMemoryHandoffBrief(options: BuildHandoffBriefOptions): string {
  const parts: string[] = ["# Memory Handoff", ""];

  if (options.query?.trim()) {
    parts.push(`## Question`, options.query.trim(), "");
  }

  if (options.answer?.trim()) {
    parts.push(`## Meta-Agent answer`, options.answer.trim(), "");
  }

  if (options.citations.length) {
    parts.push("## Sources");
    for (const c of options.citations) {
      const score = c.score != null ? ` (score ${c.score.toFixed(3)})` : "";
      parts.push(`- [${c.index}] ${c.level} · ${c.title}${score} · \`${c.memoryId}\``);
      if (c.session) {
        parts.push(
          `  - session: ${c.session.provider} \`${c.session.id}\` @ ${c.session.projectPath || "?"}`
        );
      }
    }
    parts.push("");
  }

  if (options.digests.length) {
    parts.push("## Digest excerpts");
    for (const d of options.digests.slice(0, 4)) {
      const excerpt = d.content.length > 800 ? `${d.content.slice(0, 800)}\n[...]` : d.content;
      parts.push(`### ${d.title || d.id}`, excerpt, "");
    }
  }

  const session =
    options.targetSession ||
    options.citations.find((c) => c.session)?.session;

  if (session) {
    const cmd =
      options.resumeCommand ||
      buildResumeCommandFromRef({
        provider: session.provider,
        id: session.id,
        projectPath: session.projectPath,
        title: undefined
      });
    parts.push(
      "## Resume target",
      `- Provider: ${session.provider}`,
      `- Session: \`${session.id}\``,
      `- Project: ${session.projectPath || "?"}`,
      "",
      "```bash",
      cmd,
      "```",
      ""
    );
  }

  parts.push(
    "## Suggested next step",
    "Read relevant files in the workspace before making changes. Continue from the open threads above.",
    "",
    "---",
    "Generated by Agent Resume Desktop Meta-Agent (local memory)."
  );

  return parts.join("\n");
}
